/**
 * AI Suggestion Model
 * Stores demand predictions generated by the AI service.
 * Immutable after creation (read-only analytics record).
 * Links to products and optionally to orders when a reorder is submitted.
 */

const mongoose = require('mongoose');

const aiSuggestionSchema = new mongoose.Schema(
  {
    /** Product this suggestion is for */
    productId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Product',
      required: true,
    },

    /** AI-predicted average daily demand */
    predictedDailyDemand: {
      type: Number,
      required: true,
    },

    /** Estimated days until current stock runs out */
    daysToStockout: {
      type: Number,
      required: true,
    },

    /** AI-recommended reorder quantity */
    suggestedReorderQty: {
      type: Number,
      required: true,
    },

    /** Model confidence score 0-1 */
    confidence: {
      type: Number,
      required: true,
      min: 0,
      max: 1,
    },

    /** ML method used (xgboost | heuristic) */
    method: {
      type: String,
      default: 'xgboost',
    },

    /** Inference latency in ms (for monitoring) */
    inferenceTimeMs: {
      type: Number,
      default: null,
    },

    /**
     * Workflow status
     * ACTIVE   – fresh suggestion, not yet acted upon
     * SUBMITTED – manager submitted a reorder from this suggestion
     * EXPIRED  – superseded by a newer suggestion (>24h old)
     */
    status: {
      type: String,
      enum: ['ACTIVE', 'SUBMITTED', 'EXPIRED'],
      default: 'ACTIVE',
    },

    /** The order created from this suggestion (set when manager submits reorder) */
    orderId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Order',
      default: null,
    },

    /** User who requested this AI suggestion (null for auto-generated) */
    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      default: null,
    },

    /** Business scope */
    businessId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Business',
      required: true,
    },

    /** Snapshot of product state at suggestion time (for audit) */
    snapshot: {
      productName: String,
      productSku: String,
      currentStock: Number,
      costPrice: Number,
      sellingPrice: Number,
      leadTimeDays: Number,
    },

    /** LLM health-context awareness metadata (optional, failure-safe) */
    llmContext: {
      signal: { type: String, enum: ['YES', 'NO'], default: 'NO' },
      confidence: { type: Number, min: 0, max: 1, default: 0 },
      reason: { type: String, default: '' },
      contextBoostApplied: { type: Boolean, default: false },
      boostMultiplier: { type: Number, default: 0 },
    },
  },
  {
    timestamps: true,
  }
);

/** Indexes */
aiSuggestionSchema.index({ businessId: 1, status: 1 });
aiSuggestionSchema.index({ productId: 1, createdAt: -1 });
aiSuggestionSchema.index({ createdBy: 1 });

module.exports = mongoose.model('AiSuggestion', aiSuggestionSchema);
